### ISSUE TITLE
[QA-사용성 개선] 2팀 버그

### ISSUE THREAD

**Issue by negu63** [woowa-techcamp-2021/store-8#145]
## 어떤 상황이 일어나나요?
![image](https://user-images.githubusercontent.com/86910140/131076629-1c97ce96-5a34-4439-9084-f1e32a4a34eb.png)

비 로그인 상태에서 후기 작성을 누르면
모달이 나오는데 거기서 로그인 하기를 누르고
깃허브 로그인&회원가입을 눌렀다가 
로그인&회원가입을 하지 않고 뒤로가기를 하면 상품 상세 정보가 안불러와져요

## 어떤 상황이 일어났어야 하나요?
상품 상세 정보가 표시되어야 합니다

## 의심되는 부분이 있나요?
?!

**Comment by sshrik** [comment]
해결되었습니다!
