### ISSUE TITLE
7팀 코드리뷰 

### ISSUE THREAD

**Issue by jjunyjjuny** [woowa-techcamp-2021/store-8#39]
# PR

#24 

코드리뷰량이 엄청나시군요 ..
저희는 마크업만 와다다다 했는데 벌써 어느정도 상태관리가 더해진거 같더라구요. 아주 조씁니다!

**Comment by LeagueLugas** [comment]
#29 
프로젝트 구조를 예쁘게 나누신거 같아요!!
