### ISSUE TITLE
9팀 - 코드리뷰

### ISSUE THREAD

**Issue by ag502** [woowa-techcamp-2021/store-8#84]
## 어떤 작업을 해야하나요?
- [ ] ( 0.3h ) 작업 할 내용

**Comment by ag502** [comment]
#44 #42 #66
많이 배워 갑니다 ~~~~

**Comment by jiho9505** [comment]
#44 #47
잘 보고갑니다 👍

**Comment by Hyoukjoo** [comment]
저는 종합적으로 궁금한 폴더를 찾아가 코드를 봤는데

개발 속도나 타입스크립트 완성도가 굉장히 높은거 같습니다.

서버 쪽 에러핸들링도 좋았고 앞으로 좀 더 보면서 배워갈 부분이 많은거 같아요.

화이팅~!

**Comment by junbeomAn** [comment]
#75 에 코멘트 2개 남겼습니다. 서버 개발속도가 굉장하네요. 신세 좀 지겠습니다 ㅎㅎㅎ
수고하셨어요!

**Comment by sshrik** [comment]
칭찬 너무 감사드립니다 ㅎㅎㅎ
